import {
  Merge,
  Scissors,
  RotateCw,
  Trash2,
  GripVertical,
  FileDown,
  Image,
  FileImage,
  FileText,
  Type,
  FileUp,
  Globe,
  Stamp,
  Hash,
  PenTool,
  Highlighter,
  Lock,
  Unlock,
  ScanText,
  Brain,
  type LucideIcon,
} from "lucide-react";

export type ToolCategory =
  | "organize"
  | "optimize"
  | "convert-from"
  | "convert-to"
  | "edit"
  | "security"
  | "ai";

export interface ToolDefinition {
  slug: string;
  name: string;
  description: string;
  icon: LucideIcon;
  category: ToolCategory;
  color: string;
  bgColor: string;
  acceptedFiles: string;
  multipleFiles: boolean;
  implemented: boolean;
}

export const categories: Record<
  ToolCategory,
  { label: string; color: string }
> = {
  organize: { label: "Organize", color: "text-blue-500" },
  optimize: { label: "Optimize", color: "text-emerald-500" },
  "convert-from": { label: "Convert from PDF", color: "text-orange-500" },
  "convert-to": { label: "Convert to PDF", color: "text-violet-500" },
  edit: { label: "Edit PDF", color: "text-rose-500" },
  security: { label: "Security", color: "text-amber-500" },
  ai: { label: "AI-Powered", color: "text-cyan-500" },
};

export const tools: ToolDefinition[] = [
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDFs into a single document",
    icon: Merge,
    category: "organize",
    color: "text-blue-500",
    bgColor: "bg-blue-500/10 hover:bg-blue-500/20",
    acceptedFiles: ".pdf",
    multipleFiles: true,
    implemented: true,
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Extract pages or split into multiple documents",
    icon: Scissors,
    category: "organize",
    color: "text-blue-400",
    bgColor: "bg-blue-400/10 hover:bg-blue-400/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: true,
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate pages 90, 180, or 270 degrees",
    icon: RotateCw,
    category: "organize",
    color: "text-blue-300",
    bgColor: "bg-blue-300/10 hover:bg-blue-300/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: true,
  },
  {
    slug: "remove-pages",
    name: "Remove Pages",
    description: "Delete specific pages from a PDF",
    icon: Trash2,
    category: "organize",
    color: "text-blue-600",
    bgColor: "bg-blue-600/10 hover:bg-blue-600/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "organize-pages",
    name: "Organize Pages",
    description: "Drag and drop to reorder PDF pages",
    icon: GripVertical,
    category: "organize",
    color: "text-blue-700",
    bgColor: "bg-blue-700/10 hover:bg-blue-700/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce file size while maintaining quality",
    icon: FileDown,
    category: "optimize",
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10 hover:bg-emerald-500/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: true,
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert each PDF page to a JPG image",
    icon: Image,
    category: "convert-from",
    color: "text-orange-500",
    bgColor: "bg-orange-500/10 hover:bg-orange-500/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: true,
  },
  {
    slug: "pdf-to-png",
    name: "PDF to PNG",
    description: "Convert pages to PNG with transparency",
    icon: FileImage,
    category: "convert-from",
    color: "text-orange-400",
    bgColor: "bg-orange-400/10 hover:bg-orange-400/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Extract text and formatting to DOCX",
    icon: FileText,
    category: "convert-from",
    color: "text-orange-600",
    bgColor: "bg-orange-600/10 hover:bg-orange-600/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract plain text from any PDF",
    icon: Type,
    category: "convert-from",
    color: "text-orange-300",
    bgColor: "bg-orange-300/10 hover:bg-orange-300/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert images to a PDF document",
    icon: FileUp,
    category: "convert-to",
    color: "text-violet-500",
    bgColor: "bg-violet-500/10 hover:bg-violet-500/20",
    acceptedFiles: ".jpg,.jpeg,.png,.webp,.gif",
    multipleFiles: true,
    implemented: true,
  },
  {
    slug: "png-to-pdf",
    name: "PNG to PDF",
    description: "Convert PNG images to PDF",
    icon: FileImage,
    category: "convert-to",
    color: "text-violet-400",
    bgColor: "bg-violet-400/10 hover:bg-violet-400/20",
    acceptedFiles: ".png",
    multipleFiles: true,
    implemented: false,
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert DOCX documents to PDF",
    icon: FileText,
    category: "convert-to",
    color: "text-violet-600",
    bgColor: "bg-violet-600/10 hover:bg-violet-600/20",
    acceptedFiles: ".docx,.doc",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "html-to-pdf",
    name: "HTML to PDF",
    description: "Convert web pages to PDF format",
    icon: Globe,
    category: "convert-to",
    color: "text-violet-300",
    bgColor: "bg-violet-300/10 hover:bg-violet-300/20",
    acceptedFiles: ".html,.htm",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "add-watermark",
    name: "Add Watermark",
    description: "Stamp text or image watermarks on pages",
    icon: Stamp,
    category: "edit",
    color: "text-rose-500",
    bgColor: "bg-rose-500/10 hover:bg-rose-500/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "page-numbers",
    name: "Page Numbers",
    description: "Add page numbers with custom formatting",
    icon: Hash,
    category: "edit",
    color: "text-rose-400",
    bgColor: "bg-rose-400/10 hover:bg-rose-400/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    description: "Draw or type your signature on a PDF",
    icon: PenTool,
    category: "edit",
    color: "text-rose-600",
    bgColor: "bg-rose-600/10 hover:bg-rose-600/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "annotate-pdf",
    name: "Annotate PDF",
    description: "Highlight, underline, and add text notes",
    icon: Highlighter,
    category: "edit",
    color: "text-rose-300",
    bgColor: "bg-rose-300/10 hover:bg-rose-300/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Add password encryption to your PDF",
    icon: Lock,
    category: "security",
    color: "text-amber-500",
    bgColor: "bg-amber-500/10 hover:bg-amber-500/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password protection from a PDF",
    icon: Unlock,
    category: "security",
    color: "text-amber-400",
    bgColor: "bg-amber-400/10 hover:bg-amber-400/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "ocr-pdf",
    name: "OCR",
    description: "Extract text from scanned documents",
    icon: ScanText,
    category: "ai",
    color: "text-cyan-500",
    bgColor: "bg-cyan-500/10 hover:bg-cyan-500/20",
    acceptedFiles: ".pdf,.jpg,.jpeg,.png",
    multipleFiles: false,
    implemented: false,
  },
  {
    slug: "summarize-pdf",
    name: "Summarize PDF",
    description: "AI-powered document summarization",
    icon: Brain,
    category: "ai",
    color: "text-cyan-400",
    bgColor: "bg-cyan-400/10 hover:bg-cyan-400/20",
    acceptedFiles: ".pdf",
    multipleFiles: false,
    implemented: false,
  },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return tools.filter((t) => t.category === category);
}
